<footer>
	<div class="container-full">
		<div class="col">
			<a href="#" class="mih-logo"></a>
		</div>
		<div class="col">
			<ul>
				<li>
					<a href="#">Műbank</a>
				</li>
				<li>
					<a href="#">Szerzők</a>
				</li>
				<li>
					<a href="#">Partnerek</a>
				</li>
				<li>
					<a href="#">Mi ez?</a>
				</li>
				<li>
					<a href="#">Idefigyelő</a>
				</li>
			</ul>
		</div>
		<div class="col">
			<ul>
				<li>
					<a href="#">Regény, novella</a>
				</li>
				<li>
					<a href="#">Mese</a>
				</li>
				<li>
					<a href="#">Vers</a>
				</li>
				<li>
					<a href="#">Színdarab</a>
				</li>
				<li>
					<a href="#">Tudományos cikk</a>
				</li>
				<li>
					<a href="#">Szakmai cikk</a>
				</li>
				<li>
					<a href="#">Jegyzet</a>
				</li>
			</ul>
		</div>
		<div class="col">
			<ul>
				<li>
					<a href="#">Írótanfolyam</a>
				</li>
				<li>
					<a href="#">Önkiadás</a>
				</li>
				<li>
					<a href="#">Műértékelés</a>
				</li>
			</ul>
		</div>
		<div class="col">
			<ul>
				<li>
					<a href="#">Kapcsolat</a>
				</li>
				<li>
					<a href="#">Impresszum</a>
				</li>
				<li>
					<a href="#">Adatvédelem</a>
				</li>
				<li>
					<a href="#">Hírlevél</a>
				</li>
			</ul>
		</div>
	</div>
			<div class="copyright">Minden jog fenntartva. 2016. © Magyar Irodalmi Ház</div>
</footer>
<div class="overlay"></div>
<div class="read popup">
	a
</div>
</body>
</html>