<!DOCTYPE html>
<html lang="hu">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
        <title>Magyar Irodalmi Ház</title>
        <meta name="description" content="">
        <!-- Favicons -->
        <!-- Screen CSS -->
        <link href="/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/screen.css?t=<?php echo time(); ?>" rel="stylesheet">
        <!-- 3rd-party CSS -->
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700,900&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <!-- JQuery -->
        <script src="/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/3rd-party/jquery.min.js"></script>
        <!-- 3rd-party JS files -->
        
        <!-- Main JS file -->
        <script src="/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/main.js"></script>
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </head>
    <body>
        <!--[if lt IE 9]>
        <p class="browserupgrade"><strong>Elavult</strong> böngészőt használsz. Kérlek <a href="http://browsehappy.com/">tölts le</a> újabb böngészőt, az optimális böngészés érdekében.</p>
        <![endif]-->
        <div class="color-line clear">
            <span class="color-1"></span>
            <span class="color-2"></span>
            <span class="color-3"></span>
            <span class="color-4"></span>
            <span class="color-5"></span>
            <span class="color-6"></span>
            <span class="color-7"></span>
        </div>
        <header>
            <div class="container-full">
                <div class="logo">
                    <a href="/" class="mih-logo"></a>
                </div>
                <div class="search">
                    <select>
                        <option>Mind</option>
                        <option>Novella</option>
                        <option>Regény</option>
                    </select>
                    <input type="text">
                    <button></button>
                </div>
                <div class="header-buttons">
                    <a href="#" class="upload-btn btn blue">Feltöltés</a>
                    <a href="#" class="login-btn btn grey">Belépés</a>
                </div>
            </div>
            <div class="container-full">
                <nav>
                    <ul>
                        <li><a href="/mubank">Műbank</a></li>
                        <li><a href="#">Szerzők</a></li>
                        <li><a href="#">Partnerek</a></li>
                        <li><a href="#">Idefigyelő</a></li>
                        <li><a href="#">Mi ez?</a></li>
                        <li><a href="#">Kapcsolat</a></li>
                    </ul>
                </nav>
            </div>
        </header>