<?php echo $header; ?>
<main>
	<section class="login">
		<div class="box template-1">
			<h1>Belépés</h1>
			<form>
				<div class="form-control">
					<label for="email">Email:</label>
					<input class="error" type="email">
					<div class="wrong">A mező kitöltése kötelező!</div>
				</div>
				<div class="form-control">
					<label for="password">Jelszó:</label>
					<input type="password">
				</div>
				<div class="forgot-password">
					Elfelejtettem a jelszavamat! <a href="#">Emlékeztető</a>
				</div>
				<input type="submit" class="btn black" value="Belépés">
			</form>
		</div>
	</section>
</main>
<?php echo $footer; ?>