<?php echo $header; ?>
<main>
<section class="password-modify">
	<div class="container-full">
		<div class="small-profil">
			<div class="profile-picture">
				<img alt="1" src="upload/images/author/1.png">
			</div>
			<div class="profile-details">
				<h2 class="profile-name">Hotváth Borbála Terézia</h2>
				<span class="profile-role">olvasó</span>
			</div>
		</div>
		<div class="box template-1">
			<h1>Jelszó módosítás</h1>
			<form>
				<div class="form-control">
					<label for="current-password">Jelenlegi jelszó:</label>
					<input id="current-password" class="error" type="email">
					<div class="wrong">A mező kitöltése kötelező!</div>
				</div>
				<div class="form-control">
					<label for="current-password">Új jelszó:</label>
					<input id="current password" class="error" type="email">
					<div class="wrong">A mező kitöltése kötelező!</div>
				</div>
				<input type="submit" class="btn black" value="Mentés">
			</form>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>