<?php echo $header; ?>
<main>
	<section class="password-reminder">
		<div class="box template-1">
			<h1>Jelszó emlékeztető</h1>
			<p>Add meg az email címet amivel regisztráltál és mi elküldjük rá a szükseges teendőket. Nézd meg a levélszemét között is, mert lehet hogy oda került.</p>
			<form>
				<div class="form-control">
					<label for="email">Email:</label>
					<input class="error" type="email">
					<div class="wrong">A mező kitöltése kötelező!</div>
				</div>
				<input type="submit" class="btn black" value="Küldés">
			</form>
		</div>
	</section>
</main>
<?php echo $footer; ?>