<?php echo $header; ?>
<main>
<section class="profile profile-author">
	<div class="container-full">
		<div class="sidebar">
			<div class="small-profile">
				<div class="profile-picture">
					<img alt="1" src="/upload/images/author/1.png">
				</div>
				<div class="profile-details">
					<h2 class="profile-name">Andy Weir</h2>
					<span class="profile-role">szerző</span>
				</div>
			</div>
		</div>
		<div class="content">
			<ul class="profile-menu">
				<li>
					<a href="#" class="btn active">Általános</a>
				</li>
				<li>
					<a href="#" class="btn">Műveim</a>
				</li>
				<li>
					<a href="#" class="btn">Krediteim</a>
				</li>
			</ul>
			<h1>ÁLTALÁNOS</h1>
			<div class="content-head p-d">
				<h2>Adataim</h2>
				<a href="#" class="btn edit-1 grey-mini">Szerkesztés</a>
			</div>
			<div class="profile-data clear">
				<div class="data-item">
					<span>név:</span>
					<h3>Andy Weir</h3>
				</div>
				<div class="data-item">
					<span>szerzői álnév:</span>
					<h3>-</h3>
				</div>
				<div class="data-item">
					<span>e-mail:</span>
					<h3>weir.andy@email.com</h3>
				</div>
				<div class="data-item">
					<span>telefon:</span>
					<h3>+36 20 123 4567</h3>
				</div>
			</div>
			<div class="profile-data-edit template-1">
				<div class="pop-box-head">
					<h1>Szerző</h1>
					<a href="#" class="close">×</a>
				</div>
				<h3>Profil kép</h3>
				<div class="profile-picture-edit clear">
					<div class="active-photo">
						<img src="/upload/images/author/1.png">
					</div>
					<div class="photo-edit">
						<a href="#" class="btn red-mini">Törlés</a>
						<a href="#" class="btn grey-mini">Feltöltés</a>
					</div>
				</div>
				<h3>Személyes adatok</h3>
				<form>
					<div class="pop-two-container clear">
						<div class="form-data">
							<label>Vezetéknév:</label>
							<input type="text" name="" placeholder="Weir">
						</div>
						<div class="form-data">
							<label>Keresztnév:</label>
							<input type="text" name="" placeholder="Andy">
						</div>
						<div class="form-data">
							<label>Szerzői álnév:</label>
							<input type="text" name="" placeholder="-">
						</div>
						<div class="form-data">
							<label>Születési dátum:</label>
							<input type="text" name="" placeholder="1978.11.29.">
						</div>
						<div class="form-data">
							<label>E-mail:</label>
							<input type="text" name="" placeholder="weir.andy@email.com">
						</div>
						<div class="form-data">
							<label>Telefon:</label>
							<input type="text" name="" placeholder="+36 20 123 4556">
						</div>
					</div>
					<input type="submit" value="Mentés" class="btn grey">
				</form>
			</div>
			<div class="content-head i-e">
				<h2>Bemutatkozás</h2>
				<a href="#" class="btn edit-2 grey-mini">Szerkesztés</a>
			</div>
			<div class="introduction">
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam placeat amet voluptatem quam, iure veritatis, ad atque suscipit, impedit facere, ipsam nam. Voluptate maiores, labore aspernatur eveniet! Earum, quaerat deleniti! Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
			<div class="introduction-edit template-1">
				<div class="pop-box-head">
					<h1>Szerző</h1>
					<a href="#" class="close">×</a>
				</div>
				<div>
					<h3>Bemutatkozás</h3>
				</div>
				<form>
					<div class="pop-two-container clear">
						<div class="form-data">
							<textarea>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam placeat amet voluptatem quam, iure veritatis, ad atque suscipit, impedit facere, ipsam nam. Voluptate maiores, labore aspernatur eveniet! Earum, quaerat deleniti! Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</textarea>
						</div>
					</div>
					<input type="submit" class="btn grey" value="Mentés">
				</form>
			</div>
			<div class="content-head c-e">
				<h1>ELÉRHETŐSÉG</h1>
				<a href="#" class="btn edit-3 grey-mini">Szerkesztés</a>
			</div>
			<div class="contact clear">
				<div class="mailing-address">
					<h2>Postacím:</h2>
					<div class="address-item">
						<span>Név:</span>
						<h3>Andy Weir</h3>
					</div>
					<div class="address-item">
						<span>Település:</span>
						<h3>Budapest</h3>
					</div>
					<div class="address-item">
						<span>Irányítószám:</span>
						<h3>1115</h3>
					</div>
					<div class="address-item">
						<span>Cím:</span>
						<h3>Bartók Bééla út 123. 3. emelet 5/c</h3>
					</div>
				</div>
				<div class="billing-address">
					<h2>Számlázási cím:</h2>
					<div class="address-item">
						<span>Név:</span>
						<h3>Press More Ltd.</h3>
					</div>
					<div class="address-item">
						<span>Település:</span>
						<h3>Kishalom</h3>
					</div>
					<div class="address-item">
						<span>Irányítószám:</span>
						<h3>3045</h3>
					</div>
					<div class="address-item">
						<span>Cím:</span>
						<h3>Kari utca 10.</h3>
					</div>
				</div>
			</div>
			<div class="contact-edit template-1">
				<div class="pop-box-head">
					<h1>Szerző</h1>
					<a href="#" class="close">×</a>
				</div>				
				<form>
					<div class="pop-two-container">
						<h3>Posta cím</h3>
						<div class="form-data">
							<label>Név:</label>
							<input type="text" name="" placeholder="Andy Weir">
						</div>
						<div class="form-data">
							<label>Település:</label>
							<input type="text" name="" placeholder="Budapest">
						</div>
						<div class="form-data">
							<label>Irányítószám:</label>
							<input type="text" name="" placeholder="1115">
						</div>
						<div class="form-data">
							<label>Cím:</label>
							<input type="text" name="" placeholder="Bartók Bééla út 123. 3. emelet 5/c">
						</div>
						<h3>Számlázási cím</h3>
						<div class="form-data">
							<label>Név:</label>
							<input type="text" name="" placeholder="Press More Ltd.">
						</div>
						<div class="form-data">
							<label>Település:</label>
							<input type="text" name="" placeholder="Kishalom">
						</div>
						<div class="form-data">
							<label>Irányítószám:</label>
							<input type="text" name="" placeholder="3045">
						</div>
						<div class="form-data">
							<label>Cím:</label>
							<input type="text" name="" placeholder="Kari utca 10.">
						</div>
					</div>
					<input type="submit" class="btn grey" value="Mentés">
				</form>
			</div>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>