<?php echo $header; ?>
<main class="artificial">
<div class="container-full">
	<div class="breadcrumb">
		<ul>
			<li data-title="»"><a href="#">Főoldal</a></li>
			<li data-title="»"><a href="#">Mű</a></li>
			<li><a href="#">Kiválasztott Mű</a></li>
		</ul>
	</div>
</div>
<section class="selected-artificial">
	<div class="container-full">
		<div class="sidebar">
			<div class="author-details">
				<img src="/upload/images/author/1.png" alt="1">
				<h2>Andy Weir</h2>
			</div>
			<div class="author-contact">
				<span>Telefon:</span>
				<h3>+36 30 123 4678</h3>
				<span>E-mail:</span>
				<h3>wier.andy@email.com</h3>
			</div>
			<div class="artificial-detials two clear">
				<div class="col">
					<span>Mű kelte:</span>
					<h3>2015.10.12.</h3>
				</div>
				<div class="col">
					<span>Feltöltés:</span>
					<h3>2016.06.21.</h3>
				</div>
			</div>
			<div class="artificial-detials">
				<div class="col">
					<span>Karakterszám:</span>
					<h3>14 345</h3>
				</div>
			</div>
			<div class="artificial-detials two clear">
				<div class="col">
					<span>Műfaj:</span>
					<h3>novella</h3>
				</div>
				<div class="col">
					<span>Téma:</span>
					<h3>kaland, scifi</h3>
				</div>
			</div>
			<div class="artificial-detials">
				<div class="col">
					<span>Megjelent:</span>
					<h3>Mindent Kiadó, 2015</h3>
				</div>
			</div>
			<div class="artificial-detials">
				<div class="col">
					<span>Korhatáros tartalom:</span>
					<h3>Igen</h3>
				</div>
			</div>
			<div class="artificial-detials">
				<div class="col tags">
					<ul>
						<li>
							<a class="btn brown-mini" href="#">Vadnyugat</a>
						</li>
						<li>
							<a class="btn brown-mini" href="#">Skalp</a>
						</li>
						<li>
							<a class="btn brown-mini" href="#">Meteor</a>
						</li>
						<li>
							<a class="btn brown-mini" href="#">Western</a>
						</li>
						<li>
							<a class="btn brown-mini" href="#">Űrsikló</a>
						</li>
						<li>
							<a class="btn brown-mini" href="#">Vadnyugat</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="content">
			<div class="content-head">
				<h1>A Marsi - Mentőexpedíció</h1>
				<div class="buttons">
					<a href="#" class="btn grey-mini download">Letöltöm</a>
					<a href="#" class="btn grey-mini modify is-hidden">Szerkesztés</a>
					<a href="#" class="btn brown-mini read">Elolvasom</a>
				</div>
			</div>
			<p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quibusdam placeat amet voluptatem quam, iure veritatis, ad atque suscipit, impedit facere, ipsam nam. Voluptate maiores, labore aspernatur eveniet! Earum, quaerat aliqua.</p>
			<h2>Fülszöveg:</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<h2>Keletkezése:</h2>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p>
		</div>
	</div>
</section>
</main>
<?php echo $footer; ?>