<?php echo $header; ?>
<main class="artificial">
<div class="container-full">
	<div class="breadcrumb">
		<ul>
			<li data-title="»"><a href="#">Főoldal</a></li>
			<li><a href="#">Műbank</a></li>
		</ul>
	</div>
	<h1 class="main-title">Műbank</h1>
</div>
	<section class="fiction-novels i-s-t">
		<div class="container-full">
			<h1>Regények, novellák</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
	<section class="tales i-s-t">
		<div class="container-full">
			<h1>Mesék</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
	<section class="poems i-s-t">
		<div class="container-full">
			<h1>Versek</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
	<section class="play i-s-t">
		<div class="container-full">
			<h1>Színdarabok</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
	<section class="scientific-articles i-s-t">
		<div class="container-full">
			<h1>Tudományos cikkek</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
	<section class="technical-articles i-s-t">
		<div class="container-full">
			<h1>Szakmai cikkek</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
	<section class="note i-s-t">
		<div class="container-full">
			<h1>Jegyzet</h1>
			<ul class="card-wrapper clear">
				<?php
					for ($i=0; $i < 9; $i++) {
				?>
				<li>
					<div class="item">
						<span class="category-color novel"></span>
						<a href="#">
							<img src="/upload/images/cards/1.png" alt="1">
						</a>
						<a href="#" class="item-author">Paula Hawkins</a>
						<a href="#" class="item-title">The Girls in the Train</a>
					</div>
				</li>
				<?php
				}
				?>
			</ul>
			<a href="/kategoria" class="btn brown">Tovább a teljes listához</a>
		</div>
	</section>
</main>
<?php echo $footer; ?>
